###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.5
      container_name: site_mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=livre
        - MYSQL_DATABASE=site
        - MYSQL_USER=root
        - MYSQL_PASSWORD=livre
      ports:
        - "3052:3306"

    webserver:
      image: nginx:alpine
      container_name: site-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3050:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: site-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      restart: always
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_site
      hostname: phpmyadmin
      depends_on: 
        - mysql
      ports:
        - 3051:80
      environment:
        - PMA_ARBITRARY=1   
      volumes:
        - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - /custom/phpmyadmin/theme/:/www/themes/theme/   

